title: 'Leading design'
content: 'Content relating to leading design. Things like how to organise a team, and encorage designer to do their best work find themselves in here.'
updated_by: 1a730506-93d6-4d2b-a772-38062b802324
updated_at: 1618320289
blueprint: tags
